# Generated by Django 5.0.6 on 2024-06-26 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teammember_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='datetime',
        ),
        migrations.AddField(
            model_name='teammember',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='teammember',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
