# Generated by Django 5.0.6 on 2024-06-26 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_teammember_datetime_teammember_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='date',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='time',
        ),
        migrations.AddField(
            model_name='teammember',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
